jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - continue-on-error: true
      name: Build The Bruh
      run: 'chmod +x gradlew

        ./gradlew build

        '
    - continue-on-error: true
      name: Upload The Bruh
      uses: actions/upload-artifact@v2
      with:
        name: BleachHack
        path: 'build/libs/bleachhack-*.jar

          !build/libs/bleachhack-*-*.jar

          '
name: BleachHack Workflow Builds
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
